/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ObjectService } from "../object.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ObjectCreateInput } from "./ObjectCreateInput";
import { ObjectWhereInput } from "./ObjectWhereInput";
import { ObjectWhereUniqueInput } from "./ObjectWhereUniqueInput";
import { ObjectFindManyArgs } from "./ObjectFindManyArgs";
import { ObjectUpdateInput } from "./ObjectUpdateInput";
import { Object } from "./Object";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ObjectControllerBase {
  constructor(
    protected readonly service: ObjectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Object })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: ObjectCreateInput): Promise<Object> {
    return await this.service.create({
      data: data,
      select: {
        bestAvailable: true,
        createdAt: true,
        description: true,
        endItem: true,
        id: true,
        objectAttributes: true,
        sumActualMass: true,
        sumCalculatedMass: true,
        sumDesignAndRDCost: true,
        sumEstimatedMass: true,
        sumToolingCost: true,
        sumTotalCost: true,
        title: true,
        updatedAt: true,
        url: true,
        usage: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Object] })
  @ApiNestedQuery(ObjectFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Object[]> {
    const args = plainToClass(ObjectFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        bestAvailable: true,
        createdAt: true,
        description: true,
        endItem: true,
        id: true,
        objectAttributes: true,
        sumActualMass: true,
        sumCalculatedMass: true,
        sumDesignAndRDCost: true,
        sumEstimatedMass: true,
        sumToolingCost: true,
        sumTotalCost: true,
        title: true,
        updatedAt: true,
        url: true,
        usage: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Object })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ObjectWhereUniqueInput
  ): Promise<Object | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        bestAvailable: true,
        createdAt: true,
        description: true,
        endItem: true,
        id: true,
        objectAttributes: true,
        sumActualMass: true,
        sumCalculatedMass: true,
        sumDesignAndRDCost: true,
        sumEstimatedMass: true,
        sumToolingCost: true,
        sumTotalCost: true,
        title: true,
        updatedAt: true,
        url: true,
        usage: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Object })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() data: ObjectUpdateInput
  ): Promise<Object | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          bestAvailable: true,
          createdAt: true,
          description: true,
          endItem: true,
          id: true,
          objectAttributes: true,
          sumActualMass: true,
          sumCalculatedMass: true,
          sumDesignAndRDCost: true,
          sumEstimatedMass: true,
          sumToolingCost: true,
          sumTotalCost: true,
          title: true,
          updatedAt: true,
          url: true,
          usage: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Object })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ObjectWhereUniqueInput
  ): Promise<Object | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          bestAvailable: true,
          createdAt: true,
          description: true,
          endItem: true,
          id: true,
          objectAttributes: true,
          sumActualMass: true,
          sumCalculatedMass: true,
          sumDesignAndRDCost: true,
          sumEstimatedMass: true,
          sumToolingCost: true,
          sumTotalCost: true,
          title: true,
          updatedAt: true,
          url: true,
          usage: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
